var a0;a0=argument0
switch(a0) {
    case undefined: {
    i=0 repeat(12) {
        registry_write_dword('Software\Game Maker\Version 8.2\Preferences\CodeColor'+string(i),codeColor[i])
        i+=1
    }
    } break;
    case "dialog": {
        var f;f=get_save_filename('gm82col color file|*.82col|Registry color file|*.reg|GM:S1.4 color file|*.col','')
        if f=='' exit //{show_message('Okay, cancelling saving color theme then...') exit}
        else {
            switch(filename_ext(f)) {
            case '.82col': { // new original format
                f+=string_repeat('.82col',!string_ends_with(f,'.82col'))
                ff=file_text_open_write(f)
                if ff{i=0 repeat(12) {
                    file_text_write_string(ff,lname[i]+';'+string(codeColor[i]));
                    file_text_writeln(ff)
                    i+=1
                }}
            file_text_close(ff)
            } break;
            case '.col': { // xml file
                f+=string_repeat('.col',!string_ends_with(f,'.col'))
                ff=file_text_open_write(f)
                file_text_write_string(ff,'<!--This Document is generated by GameMaker, if you edit it by hand then you do so at your own risk!-->')
                file_text_writeln(ff)
                file_text_write_string(ff,'<Colours>')
                file_text_writeln(ff)
                if ff{i=0 repeat(12) {
                    file_text_write_string(ff,'  <Color'+string(i)+'>'+string(codeColor[i])+'</Color'+string(ii)+'>');
                    file_text_writeln(ff)
                    i+=1
                }}
                file_text_write_string(ff,'</Colours>')
            file_text_close(ff)
            } break;
            case '.reg': { // registry files
                f+=string_repeat('.reg',!string_ends_with(f,'.reg'))
                ff=file_text_open_write(f)
                file_text_write_string(ff,'Windows Registry Editor Version 5.00')
                repeat 2 file_text_writeln(ff)
                file_text_write_string(ff,'[HKEY_CURRENT_USER\Software\Game Maker\Version 8.2\Preferences]')
                file_text_writeln(ff)
                i=0 repeat(12) {
                    file_text_write_string(ff,'"CodeColor'+string(i)+'"=dword:00'+string_hex(codeColor[i]))
                    file_text_writeln(ff)
                i+=1
                }
                file_text_close(ff)
            } break;
            }
        }
    } break;
}
